trigger:
- main
- feature/*
pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  GitVersion.NuGetVersion: ''
  solution: '**/*.sln'

jobs:
- job: package
  displayName: 'Build, pack and push'
  continueOnError: false
  steps:


  - task: gitversion/setup@0
    displayName: 'Install GitVersion'
    inputs:
      versionSpec: '5.7.0'
  
  - task: gitversion/execute@0
    displayName: 'Execute GitVersion'

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '6.0.101'
      includePreviewVersions: true

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      command: 'build'
      projects: '$(solution)'
      arguments: '--configuration $(buildConfiguration) -p:Version=$(GitVersion.NuGetVersion)'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet pack'
    inputs:
        command: 'pack'
        packagesToPack: '$(solution)'
        nobuild: true
        packDirectory: '$(Build.ArtifactStagingDirectory)'
        versioningScheme: 'byEnvVar'
        versionEnvVar: 'GitVersion.NuGetVersion'
  
  - task: NuGetCommand@2
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'external'
      publishFeedCredentials: 'Nuget-Push'